=== HarryLack/ProgressionLeague-v1/src/lists/listSchema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Banlist",
  "description": "A Banlist for progression league",
  "type": "object",
  "properties": {
    "lastChanged": {
      "type": "string"
    },
    "banned": {
      "type": "array"
    },
    "limited": {
      "type": "array"
    },
    "semiLimited": {
      "type": "array"
    }
  }
}

=== HarryLack/ProgressionLeague-v1/lists/newList.json
{
  "lastChanged": "Week 34",
  "banned": [
    "1357146",
    "78864369",
    "70828912",
    "4031928",
    "78706415",
    "3078576",
    "28566710",
    "57585212",
    "17375316",
    "44763025",
    "42829885",
    "12580477",
    "45986603",
    "79571449",
    "63519819",
    "72989439",
    "35316708",
    "69015963",
    "18144507",
    "34124316",
    "41482598",
    "74191942",
    "78010363",
    "85602018",
    "83764719",
    "53129443",
    "55144522",
    "34206604",
    "19613556",
    "64697231",
    "93016201"
  ],
  "limited": [
    "14878871",
    "27053506",
    "63665875",
    "2009101",
    "65192027",
    "77585513",
    "12607053",
    "40044918",
    "23205979",
    "61740673",
    "42703248",
    "97077563",
    "44656491",
    "44095762",
    "53582587",
    "82301904",
    "29401950",
    "41420027",
    "81674782",
    "57953380",
    "33508719",
    "87910978",
    "82732705",
    "85742772",
    "3136426",
    "91623717",
    "80344569",
    "37742478",
    "30241314",
    "67169062",
    "73580471",
    "9596126",
    "94192409",
    "23557835",
    "75500286",
    "44330098",
    "37520316",
    "33420078",
    "32807846",
    "27174286",
    "72892473"
  ],
  "semiLimited": [
    "9411399",
    "26202165",
    "85215458",
    "91351370"
  ]
}

=== HarryLack/ProgressionLeague-v1/src/lists/W12.5.json
{
  "lastChanged": "DM EoE",
  "banned": [
    "4031928",
    "78706415",
    "3078576",
    "28566710",
    "57585212",
    "17375316",
    "44763025",
    "42829885",
    "12580477",
    "45986603",
    "53129443",
    "79571449",
    "63519819"
  ],
  "limited": [
    "83764719",
    "55144522",
    "34124316",
    "19613556",
    "61740673",
    "77585513",
    "42703248",
    "78010363",
    "71413901",
    "97077563",
    "34206604",
    "44656491",
    "44095762",
    "74191942",
    "70828912",
    "72989439",
    "74131780",
    "85602018",
    "31560081",
    "41482598",
    "32807846",
    "23205979",
    "53582587",
    "33184167"
  ],
  "semiLimited": [
    "26202165",
    "71044499",
    "85742772"
  ]
}
